# Configuration file artifacts.

metadata:
  format_version: 20150618
  definition_type: artifact
---
name: SshdConfigFile
doc: Sshd configuration
sources:
- type: FILE
  attributes: {paths: ['/etc/ssh/sshd_config']}
labels: [Configuration Files]
supported_os: [Linux]
---
name: NfsExportsFile
doc: NFS Exports configuration
sources:
- type: FILE
  attributes: {paths: ['/etc/exports']}
labels: [Configuration Files]
supported_os: [Linux, Darwin]
